<?php
/**
 * @package   Infosys/EPCconnect
 * @version   1.0.0
 * @author    Infosys Limited
 * @copyright Copyright © 2021. All Rights Reserved.
 */

/* @var $block \Infosys\EPCconnect\Block\System\Config\Connection */ ?>
<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery){

        var collectSpan = jQuery('#collect_span');

        jQuery('#connection_button').click(function () {
            var params = {};
            new Ajax.Request('<?= /* @noEscape */ $block->getAjaxUrl() ?>', {
                parameters:     params,
                loaderArea:     false,
                asynchronous:   true,
                dataType: "json",
                onCreate: function() {
                    collectSpan.find('.collected').hide();
                    collectSpan.find('.processing').show();
                    jQuery('#collect_message_span').text('');
                },
                onSuccess: function(response) {
                    collectSpan.find('.processing').hide();
                    var result = JSON.parse(response.responseText);
                    var resultText = '';
                    if (response.status > 200) {
                        resultText = response.statusText;
                    } else {
                        if(result.status==true){
                            resultText = 'Success';
                            collectSpan.find('.collected').show();
                        }else{
                            resultText = 'Failed!';
                        }
                    }
                    jQuery('#collect_message_span').text(resultText);
                }
            });
        });

    });
</script>

<?= $block->getButtonHtml() ?>
<span class="collect-indicator" id="collect_span">
    <img class="processing" hidden="hidden" alt="Collecting" style="margin:0 5px" 
        src="<?= /* @noEscape */ $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <img class="collected" hidden="hidden" alt="Collected" style="margin:-3px 5px" 
        src="<?= /* @noEscape */ $block->getViewFileUrl('images/rule_component_apply.gif') ?>"/>
    <span id="collect_message_span"></span>
</span>