<?php

/**
 * @package     Infosys/OrderView
 * @version     1.0.0
 * @author      Infosys Limited
 * @copyright   Copyright © 2021. All Rights Reserved.
 */

/** @var $block \Magento\Framework\View\Element\Template */
//phpcs:disable Magento2.Files.LineLength.MaxExceeded

$parentBlock = $block->getParentBlock();
$track = $block->getData('track');
$number = is_object($track) ? $track->getTracking() : $track['number'];
?>
<table class="data table order tracking" id="tracking-table-popup-<?= $block->escapeHtml($number) ?>">
    <caption class="table-caption"><?= $block->escapeHtml(__('Order tracking')) ?></caption>
    <tbody>
        <?php if (is_object($track)) : ?>
            <tr>
                <th class="col label" scope="row"><?= $block->escapeHtml(__('Tracking Number:')) ?></th>
                <td>
                    <?php if (strtolower($track->getCarrier()) == 'dhl') : ?>
                        <a id="col-track-<?= $number ?>" href="<?= $parentBlock->getShipmentTrackingLink($track->getCarrier(), $number) ?>">
                            <?= $block->escapeHtml($number) ?>
                        </a>
                    <?php elseif (strtolower($track->getCarrier()) == 'fedex') : ?>
                        <a id="col-track-<?= $number ?>" href="<?= $parentBlock->getShipmentTrackingLink($track->getCarrier(), $number) ?>">
                            <?= $block->escapeHtml($number) ?>
                        </a>
                    <?php elseif (strtolower($track->getCarrier()) == 'ups') : ?>
                        <a id="col-track-<?= $number ?>" href="<?= $parentBlock->getShipmentTrackingLink($track->getCarrier(), $number) ?>">
                            <?= $block->escapeHtml($number) ?>
                        </a>
                    <?php elseif (strtolower($track->getCarrier()) == 'usps') : ?>
                        <a id="col-track-<?= $number ?>" href="<?= $parentBlock->getShipmentTrackingLink($track->getCarrier(), $number) ?>">
                            <?= $block->escapeHtml($number) ?>
                        </a>
                    <?php else : ?>
                        <?= $block->escapeHtml($number) ?>
                    <?php endif; ?>
                </td>
            </tr>
            <?php if ($track->getCarrierTitle()) : ?>
                <tr>
                    <th class="col label" scope="row"><?= $block->escapeHtml(__('Carrier:')) ?></th>
                    <td class="col value"><?= $block->escapeHtml($track->getCarrierTitle()) ?></td>
                </tr>
            <?php endif; ?>
        <?php elseif (isset($track['title']) && isset($track['number']) && $track['number']) : ?>
            <?php /* if the tracking is custom value */ ?>
            <tr>
                <th class="col label" scope="row">
                    <?= ($track['title'] ? $block->escapeHtml($track['title']) : $block->escapeHtml(__('N/A'))) ?>:
                </th>
                <td class="col value"><?= (isset($track['number']) ? $block->escapeHtml($track['number']) : '') ?></td>
            </tr>
        <?php endif; ?>
    </tbody>
</table>